info:
  version: 1.0.3
  description: AUSF initial local configuration
configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.9
    bindingIPv4: 127.0.0.9
    port: 8000
    tls:
      pem: cert/ausf.pem
      key: cert/ausf.key
  serviceNameList:
  - nausf-auth
  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem
  plmnSupportList:
  - mcc: 208
    mnc: 93
  - mcc: 123
    mnc: 45
  groupId: ausfGroup001
  eapAkaSupiImsiPrefix: false
  metrics:
    enable: true
    scheme: http
    bindingIPv4: 127.0.0.9
    port: 9096
    namespace: free5gc
logger:
  enable: true
  level: info
  reportCaller: false
metrics:
  enable: true
  scheme: http
  bindingIPv4: 127.0.0.9
  port: 9096
  namespace: free5gc
