info:
  version: 1.0.2
  description: NSSF local configuration 208/93

configuration:
  nssfName: NSSF
  sbi:
    scheme: http
    registerIPv4: 127.0.0.31
    bindingIPv4: 127.0.0.31
    port: 8000
    tls:
      pem: cert/nssf.pem
      key: cert/nssf.key
  serviceNameList:
    - nnssf-nsselection
    - nnssf-nssaiavailability
  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem

  supportedPlmnList:
    - mcc: 208
      mnc: 93

  supportedNssaiInPlmnList:
    - plmnId:
        mcc: 208
        mnc: 93
      supportedSnssaiList:
        - sst: 1
          sd: 001083
        - sst: 1
          sd: 01B669

  nsiList:
    - snssai:
        sst: 1
        sd: 001083
      nsiInformationList:
        - nrfId: http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances
          nsiId: 1
    - snssai:
        sst: 1
        sd: 01B669
      nsiInformationList:
        - nrfId: http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances
          nsiId: 2

  taList:
    - tai:
        plmnId:
          mcc: 208
          mnc: 93
        tac: 000001
      accessType: 3GPP_ACCESS
      supportedSnssaiList:
        - sst: 1
          sd: 001083
        - sst: 1
          sd: 01B669

  amfSetList: []
  amfList: []
  mappingListFromPlmn: []

  metrics:
    enable: true
    scheme: http
    bindingIPv4: 127.0.0.31
    port: 9098
    namespace: free5gc

logger:
  enable: true
  level: info
  reportCaller: false

metrics:
  enable: true
  scheme: http
  bindingIPv4: 127.0.0.31
  port: 9098
  namespace: free5gc
