info:
  version: 1.1.0
  description: UDR initial local configuration
configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.4
    bindingIPv4: 127.0.0.4
    port: 8000
    tls:
      pem: cert/udr.pem
      key: cert/udr.key
  dbConnectorType: mongodb
  mongodb:
    name: free5gc
    url: mongodb://localhost:27017
  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem
  metrics:
    enable: true
    scheme: http
    bindingIPv4: 127.0.0.4
    port: 9095
    namespace: free5gc
logger:
  enable: true
  level: info
  reportCaller: false
metrics:
  enable: true
  scheme: http
  bindingIPv4: 127.0.0.4
  port: 9095
  namespace: free5gc
